### ISSUE TITLE
geoplot package installation

### ISSUE THREAD

**Issue by mxfh** [jorisvandenbossche/geopandas-tutorial#2]
don't know if it's just my zoo, but geoplot isn't in the default channels of vanilla miniconda. 
so you need to install it manually after miniconda 

    conda install -c conda-forge geoplot 

or add the conda forge-channel before getting all the packages

    conda config --add channels conda-forge

**Comment by jorisvandenbossche** [comment]
Yes, thanks for the report, that was indeed an error in the instructions (on my laptop I have conda-forge added to my channels as default, so didn't notice that)

**Comment by jorisvandenbossche** [comment]
Fixed in https://github.com/jorisvandenbossche/geopandas-tutorial/commit/0ee574c336654de8891fab4ee4f2bf035f492ad9
