### ISSUE TITLE
AttributeError: 'GeoDataFrame' object has no attribute 'show'

### ISSUE THREAD

**Issue by song-zi** [jorisvandenbossche/geopandas-tutorial#7]
anaconda3 + vscode + win10

in 01,when i use show(), vscode return AttributeError: 'GeoDataFrame' object has no attribute 'show'.
i can get a basic visualization of the data

**Comment by jorisvandenbossche** [comment]
For a basic visualization, you can use the `plot()` method

**Comment by jorisvandenbossche** [comment]
For a basic visualization, you can use the `plot()` method
